version: '2.1'
services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
       - 80:80
       - 443:443
    restart: on-failure
    volumes:
      - /opt/nginx:/config:rw
      - /opt/nginx:/etc/nginx:rw
      - /opt/nginx/conf.d:/etc/nginx/conf.d:rw
      - /opt/nginx/log:/config/log/nginx:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      influxdb:
        condition: service_healthy
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - /opt/grafana:/etc/grafana:rw
      - /opt/grafana:/var/lib/grafana:rw

  influxdb:
    image: influxdb
    container_name: influxdb
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 24
    network_mode: host
    ports:
      - 8086:8086
    restart: on-failure
    volumes:
      - /opt/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /opt/influxdb:/var/lib/influxdb

  homeassistant:
    #image: homeassistant/home-assistant:dev
    image: homeassistant/home-assistant
    container_name: home-assistant
    depends_on:
      influxdb:
        condition: service_healthy
      mosquitto:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6
    network_mode: host
    ports:
      - "8123:8123"
    restart: on-failure
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/localtime:/etc/localtime:ro

  hass_playground:
    #image: homeassistant/home-assistant:dev
    image: homeassistant/home-assistant
    container_name: hass_playground
    depends_on:
      influxdb:
        condition: service_healthy
      mosquitto:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6
    #network_mode: host
    ports:
      - "9123:8123"
    #restart: on-failure
    volumes:
      - /opt/homeassistant/config_dev:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/localtime:/etc/localtime:ro

  node-red:
    #image: nodered/node-red-docker
    image: machinedata/node-red
    container_name: node-red
    depends_on:
      mosquitto:
        condition: service_started
      homeassistant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:1880"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 1880:1880
    restart: on-failure
    volumes:
      - /opt/node-red:/data
      #- /usr/src/node-red:/usr/src/node-red
      #- /usr/bin:/usr/local/bin
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: "1000:1000"
    ports:
      - 1883:1883
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mosquitto:/mosquitto/config:ro
      - /opt/mosquitto:/mosquitto/data

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    restart: on-failure
    volumes:
      - /opt/portainer:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock

  #organizr:
  #  container_name: organizr
  #  image: lsiocommunity/organizr
  #  environment:
  #    - PGID=1000
  #    - PUID=1000
  #  healthcheck:
  #    test: ["CMD", "curl", "-f", "http://127.0.0.1"]
  #    interval: 30s
  #    timeout: 10s
  #    retries: 5
  #  ports:
  #    - 80:80
  #    - 443:443
  #  restart: on-failure
  #  volumes:
  #    - /opt/organizr:/config:rw
  #    - /etc/letsencrypt:/etc/letsencrypt:ro

  dockermon:
    image: philhawthorne/ha-dockermon
    container_name: dockermon
    ports:
      - 8126:8126
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/dockermon:/config

  #appdaemon:
  #  container_name: homeassistant_appdaemon
  #  image: acockburn/appdaemon:latest
  #  depends_on:
  #    - homeassistant
  #  links:
      # Link ports from home-assistant container
  #    - homeassistant
  #  ports:
  #    - 5050:5050
  #  restart: on-failure
  #  volumes:
  #    - /opt/appdaemon:/conf
  #    - /etc/localtime:/etc/localtime:ro

  unifi:
    image: jacobalberty/unifi:latest
    container_name: "unifi"
    environment:
      - TZ=America/Los_Angeles
    network_mode: "host"
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 6789:6789/tcp
      - 8080:8080/tcp
      - 8880:8880/tcp
      - 8443:8443/tcp
      - 8843:8843/tcp
    restart: on-failure
    volumes:
      - /opt/unifi/data:/unifi/data

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    command: --cleanup --label-enable
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/watchtower/config.json:/config.json:ro